// const LOGIN_WITH_PROVIDER_FIREBASE = 'LOGIN_WITH_PROVIDER_FIREBASE';
// const REGISTER_FIREBASE_USER = 'REGISTER_FIREBASE_USER';
// const LOGIN_FIREBASE_USER = 'LOGIN_FIREBASE_USER';
// const LOGIN_FIREBASE_USER_SUCCESS = 'LOGIN_FIREBASE_USER_SUCCESS';
// const FETCH_FIREBASE_USER = 'FETCH_FIREBASE_USER';
// const UPDATE_FIREBASE_USER = 'UPDATE_FIREBASE_USER';
// const CHANGE_FIREBASE_USER_PASSWORD = 'CHANGE_FIREBASE_USER_PASSWORD';
// const FIREBASE_PASSWORD_RESET_EMAIL = 'FIREBASE_PASSWORD_RESET_EMAIL';
// const LOGOUT_FIREBASE_USER = 'LOGOUT_FIREBASE_USER';

// export default ({
//   LOGIN_WITH_PROVIDER_FIREBASE,
//   REGISTER_FIREBASE_USER,
//   LOGIN_FIREBASE_USER,
//   LOGIN_FIREBASE_USER_SUCCESS,
//   FETCH_FIREBASE_USER,
//   UPDATE_FIREBASE_USER,
//   CHANGE_FIREBASE_USER_PASSWORD,
//   FIREBASE_PASSWORD_RESET_EMAIL,
//   LOGOUT_FIREBASE_USER,
// });

const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';
const LOGIN_USER = 'LOGIN_USER';

export default ({
  LOGIN_USER_SUCCESS,
  LOGIN_USER_FAIL,
  LOGIN_USER,
});
