const SAVE_DETAIL = 'SAVE_DETAILS';
const SAVE_DETAIL_SUCCESS = 'SAVE_DETAILS_SUCCESS';
const SAVE_DETAIL_FAILURE = 'SAVE_DETAILS_FAILURE';

export default ({ SAVE_DETAIL, SAVE_DETAIL_SUCCESS, SAVE_DETAIL_FAILURE });
