const UPLOAD_ITEM = 'UPLOAD_ITEM';
const UPLOAD_ITEM_SUCCESS = 'UPLOAD_ITEM_SUCCESS';
const UPLOAD_ITEM_FAILURE = 'UPLOAD_ITEM_FAILURE';

export default ({ UPLOAD_ITEM, UPLOAD_ITEM_SUCCESS, UPLOAD_ITEM_FAILURE });
